INSERT INTO `appointments` (`id`, `user_id`, `doctor_id`, `hospital_id`, `session_id`, `appointment_date`, `token_number`, `token_locked_at`, `token_lock_expires_at`, `token_status`, `missed_appointment`, `no_show_reason`, `token_changed_count`, `original_token_number`, `last_token_change_at`, `estimated_time`, `actual_start_time`, `actual_end_time`, `consultation_started_at`, `consultation_ended_at`, `status`, `booking_type`, `patient_complaints`, `doctor_notes`, `prescription`, `consultation_fee`, `created_at`, `updated_at`, `is_recalled`, `recall_count`, `last_recalled_at`, `attended_after_recall`) VALUES
('appt-tests3-001', 'test-user--001', 'doc-lYmc71t79BFF', 'gmc-kottayam-OeSnZmuiLV', 'sess-sSWSlQ6lyCMG', '2025-10-10', 1, NULL, NULL, 'pending', 0, NULL, 0, NULL, NULL, '09:00', NULL, NULL, NULL, NULL, 'confirmed', 'grid', 'Headache and fever', NULL, NULL, 500.00, NOW(), NOW(), 0, 0, NULL, 0),
('appt-tests3-002', 'test-user--002', 'doc-lYmc71t79BFF', 'gmc-kottayam-OeSnZmuiLV', 'sess-sSWSlQ6lyCMG', '2025-10-10', 2, NULL, NULL, 'pending', 0, NULL, 0, NULL, NULL, '09:15', NULL, NULL, NULL, NULL, 'confirmed', 'grid', 'Breathing difficulty', NULL, NULL, 500.00, NOW(), NOW(), 0, 0, NULL, 0),
('appt-tests3-003', 'test-user--003', 'doc-lYmc71t79BFF', 'gmc-kottayam-OeSnZmuiLV', 'sess-sSWSlQ6lyCMG', '2025-10-10', 3, NULL, NULL, 'pending', 0, NULL, 0, NULL, NULL, '09:30', NULL, NULL, NULL, NULL, 'confirmed', 'grid', 'Blood sugar check', NULL, NULL, 500.00, NOW(), NOW(), 0, 0, NULL, 0),
('appt-tests3-004', 'test-user--004', 'doc-lYmc71t79BFF', 'gmc-kottayam-OeSnZmuiLV', 'sess-sSWSlQ6lyCMG', '2025-10-10', 4, NULL, NULL, 'pending', 0, NULL, 0, NULL, NULL, '09:45', NULL, NULL, NULL, NULL, 'confirmed', 'grid', 'High BP consultation', NULL, NULL, 500.00, NOW(), NOW(), 0, 0, NULL, 0),
('appt-tests3-005', 'test-user--005', 'doc-lYmc71t79BFF', 'gmc-kottayam-OeSnZmuiLV', 'sess-sSWSlQ6lyCMG', '2025-10-10', 5, NULL, NULL, 'pending', 0, NULL, 0, NULL, NULL, '10:00', NULL, NULL, NULL, NULL, 'confirmed', 'grid', 'General checkup', NULL, NULL, 500.00, NOW(), NOW(), 0, 0, NULL, 0),
('appt-tests3-006', 'test-user--006', 'doc-lYmc71t79BFF', 'gmc-kottayam-OeSnZmuiLV', 'sess-sSWSlQ6lyCMG', '2025-10-10', 6, NULL, NULL, 'pending', 0, NULL, 0, NULL, NULL, '10:15', NULL, NULL, NULL, NULL, 'confirmed', 'grid', 'Thyroid follow-up', NULL, NULL, 500.00, NOW(), NOW(), 0, 0, NULL, 0),
('appt-tests3-007', 'test-user--007', 'doc-lYmc71t79BFF', 'gmc-kottayam-OeSnZmuiLV', 'sess-sSWSlQ6lyCMG', '2025-10-10', 7, NULL, NULL, 'pending', 0, NULL, 0, NULL, NULL, '10:30', NULL, NULL, NULL, NULL, 'confirmed', 'grid', 'Stomach pain', NULL, NULL, 500.00, NOW(), NOW(), 0, 0, NULL, 0),
('appt-tests3-008', 'test-user--008', 'doc-lYmc71t79BFF', 'gmc-kottayam-OeSnZmuiLV', 'sess-sSWSlQ6lyCMG', '2025-10-10', 8, NULL, NULL, 'pending', 0, NULL, 0, NULL, NULL, '10:45', NULL, NULL, NULL, NULL, 'confirmed', 'grid', 'Severe migraine', NULL, NULL, 500.00, NOW(), NOW(), 0, 0, NULL, 0),
('appt-tests3-009', 'test-user--009', 'doc-lYmc71t79BFF', 'gmc-kottayam-OeSnZmuiLV', 'sess-sSWSlQ6lyCMG', '2025-10-10', 9, NULL, NULL, 'pending', 0, NULL, 0, NULL, NULL, '11:00', NULL, NULL, NULL, NULL, 'confirmed', 'grid', 'Routine checkup', NULL, NULL, 500.00, NOW(), NOW(), 0, 0, NULL, 0),
('appt-tests3-010', 'test-user--010', 'doc-lYmc71t79BFF', 'gmc-kottayam-OeSnZmuiLV', 'sess-sSWSlQ6lyCMG', '2025-10-10', 10, NULL, NULL, 'pending', 0, NULL, 0, NULL, NULL, '11:15', NULL, NULL, NULL, NULL, 'confirmed', 'grid', 'Joint pain', NULL, NULL, 500.00, NOW(), NOW(), 0, 0, NULL, 0);
